[project]
name = "azure-blob-backup-manager"
version = "1.0.3"
description = "A small utility to smartly manage backups in an Azure Blob container"
dependencies = [
    "azure-storage-blob==12.26.0",
    "harp-logfmt-python @ git+https://github.com/HARP-research-Inc/logfmt-python.git@1.2.0",
    "pydantic==2.12.4",
]
requires-python = ">=3.13"

[[project.authors]]
name = "HARP Research"
email = "dev@harpresearch.ai"

[project.optional-dependencies]
lint = ["ruff==0.12.9"]
test = ["pytest==8.4.1"]
dev = ["azure-blob-backup-manager[lint,test]"]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
